const { test } = require('node:test');
const { close } = require('./helpers/close.js');
const ta = require('../index.js');
const p = require('./parameters.js');

const fx = (name, call) =>
  test(name, () => close((call || (() => ta[name].apply(null, p[name].in)))(), p[name].out));

fx('macd');
fx('macd_signal');
fx('macd_bars');
fx('rsi');
fx('wrsi');
fx('tsi');
fx('bop');
fx('fi');
fx('asi');
fx('alligator');
fx('pr');
fx('stoch');
fx('fib');
fx('bandwidth');
fx('ichimoku');
fx('atr');
fx('mfi');
fx('roc');
fx('cop');
fx('kst');
fx('obv');
fx('vwap');
fx('fractals');
fx('fractals_price', () => ta.fractals.apply(null, p.fractals_price.in));
fx('cross');
fx('mom');
fx('halftrend');
fx('zigzag');

fx('zigzag_close', () => ta.zigzag.apply(null, p.zigzag_close.in));
fx('psar');
fx('supertrend');
fx('elderray');
fx('hv');
fx('rvi');
fx('rvi_signal');
fx('rsi_divergence');
fx('divergence');
fx('trix');
fx('adl');
fx('cci');
fx('pdm');
fx('mdm');
fx('pdi');
fx('mdi');
fx('dx');
fx('adx');
fx('adxr');
fx('stoch_rsi');
fx('ppo');
fx('apo');
fx('cmf');
fx('nvi');
fx('pvi');
fx('emv');
fx('natr');
fx('dpo');
fx('mass');
fx('ulcer');
fx('vortex');
fx('kdj');

fx('aroon_up',   () => ta.aroon.up.apply(null,   p.aroon_up.in));
fx('aroon_down', () => ta.aroon.down.apply(null, p.aroon_down.in));
