// Single source of truth for bench coverage. One entry per ta.js export.
//
// status:
//   'cross-lib'  — has comparison adapters in cases/<category>.js (≥1 competitor)
//   'solo'       — has a ta.js-only adapter in cases/<category>.js (regression tracking)
//   'excluded'   — intentionally not benched; `reason` documents why
//
// `caseName` is set only when the bench case name differs from the ta.js
// export name (e.g. ta.bands → case 'bbands', ta.aroon.up → case 'aroon_up').
//
// `libs` is set on cross-lib entries to record which competitors implement
// the function. Used by COVERAGE.md to render the comparison matrix.
//
// Adding a new export to ta.js requires adding a row here. The drift
// validator (`bench/coverage-report.js`) exits non-zero if any export lacks
// a coverage row, or any row points at a missing export / missing case.

module.exports = [
  // === moving averages ===
  { name: 'sma',   category: 'moving-averages', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'ema',   category: 'moving-averages', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'wma',   category: 'moving-averages', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'],
    notes: 'debut.LWMA is semantically equivalent.' },
  { name: 'smma',  category: 'moving-averages', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'],
    notes: 'ti.WEMA / ts.WSMA / debut.SMMA / tulind.wilders all compute Wilder smoothing.' },
  { name: 'hull',  category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'], notes: 'tulind.hma.' },
  { name: 'kama',  category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'], notes: 'Param convention diverges; expect Δ.' },
  { name: 'vwma',  category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 'pwma',  category: 'moving-averages', status: 'solo' },
  { name: 'hwma',  category: 'moving-averages', status: 'solo' },
  { name: 'cwma',  category: 'moving-averages', status: 'solo' },
  { name: 'lsma',  category: 'moving-averages', status: 'solo' },
  { name: 'vwwma', category: 'moving-averages', status: 'solo' },
  { name: 'wsma',  category: 'moving-averages', status: 'solo',
    notes: 'Alias of smma (covered cross-lib).' },
  { name: 'dema',  category: 'moving-averages', status: 'cross-lib',
    libs: ['trading-signals', 'tulind'] },
  { name: 'tema',  category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 'trima', category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 't3',    category: 'moving-averages', status: 'solo',
    notes: 'Tilson T3 — not in any installed competitor lib (TA-Lib only).' },
  { name: 'zlema', category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 'vidya', category: 'moving-averages', status: 'cross-lib',
    libs: ['tulind'], notes: 'Chande adaptive MA. Signature matches tulind: (data, short, long, alpha).' },

  // === indicators ===
  { name: 'macd',           category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'macd_signal',    category: 'indicators', status: 'excluded',
    reason: 'sub-component of macd (covered cross-lib).' },
  { name: 'macd_bars',      category: 'indicators', status: 'excluded',
    reason: 'sub-component of macd (covered cross-lib).' },
  { name: 'rsi',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'wrsi',           category: 'indicators', status: 'solo',
    notes: 'Alias of rsi (covered cross-lib).' },
  { name: 'tsi',            category: 'indicators', status: 'solo' },
  { name: 'bop',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 'fi',             category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators'] },
  { name: 'asi',            category: 'indicators', status: 'solo' },
  { name: 'alligator',      category: 'indicators', status: 'solo' },
  { name: 'pr',             category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', 'tulind'],
    notes: 'ta.js takes a close-only series; competitors take HLC.' },
  { name: 'stoch',          category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'fib',            category: 'indicators', status: 'solo',
    notes: 'Microbenchmark — single call returning 11 retracement levels.' },
  { name: 'bandwidth',      category: 'indicators', status: 'solo' },
  { name: 'ichimoku',       category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators'] },
  { name: 'atr',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'mfi',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', '@debut/indicators', 'tulind'] },
  { name: 'roc',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'],
    notes: 'tulind returns fraction; everyone else returns percent. Bench uses TI as reference.' },
  { name: 'cop',            category: 'indicators', status: 'solo' },
  { name: 'kst',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators'] },
  { name: 'obv',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', 'tulind'] },
  { name: 'vwap',           category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators'] },
  { name: 'fractals',       category: 'indicators', status: 'solo' },
  { name: 'cross',          category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'tulind.crossany — boolean → 0/1 mapping.' },
  { name: 'mom',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 'halftrend',      category: 'indicators', status: 'solo' },
  { name: 'zigzag',         category: 'indicators', status: 'solo' },
  { name: 'psar',           category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'supertrend',     category: 'indicators', status: 'cross-lib',
    libs: ['@debut/indicators'], notes: 'ta.js outputs band pair; debut outputs full trend state.' },
  { name: 'elderray',       category: 'indicators', status: 'solo' },
  { name: 'hv',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'tulind.volatility.' },
  { name: 'rvi',            category: 'indicators', status: 'solo' },
  { name: 'rvi_signal',     category: 'indicators', status: 'solo' },
  { name: 'rsi_divergence', category: 'indicators', status: 'solo' },
  { name: 'divergence',     category: 'indicators', status: 'solo' },
  { name: 'trix',           category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'tulind'] },
  { name: 'adl',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'tulind'], notes: 'Chaikin A/D Line. tulind exposes as ad.' },
  { name: 'cci',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'pdm',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'ta.js uses TA-Lib seeding (sum of length raw +DM); tulind uses single-value seed and may diverge.' },
  { name: 'mdm',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'See pdm for seeding convention note.' },
  { name: 'pdi',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', '@debut/indicators', 'tulind'],
    notes: 'TA-Lib convention. Bit-matches ti.ADX.pdi and debut.ADX.pdi. Diverges from tulind early bars.' },
  { name: 'mdi',            category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', '@debut/indicators', 'tulind'], notes: 'See pdi.' },
  { name: 'dx',              category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Diverges from tulind in early bars; matches ti.ADX/debut.ADX intermediate after warmup.' },
  { name: 'adx',             category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'],
    notes: 'TA-Lib convention. Bit-matches ti.ADX.adx and debut.ADX.adx; diverges from tulind/ts.ADX which use early-output seeding.' },
  { name: 'adxr',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'See adx for seeding convention.' },
  { name: 'stoch_rsi',       category: 'indicators', status: 'cross-lib',
    libs: ['technicalindicators', '@debut/indicators'],
    notes: 'Returns array of [fastK, fastD] pairs (smoothed). tulind.stochrsi and ts.StochasticRSI return raw fastK in [0,1] without smoothing — semantically different functions, excluded from cross-lib comparison.' },
  { name: 'ppo',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Percentage Price Oscillator. Tulind uses streaming EMA seed; tail values converge.' },
  { name: 'apo',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Absolute Price Oscillator (= MACD line with EMA MA-type). See ppo for tulind divergence.' },
  { name: 'cmf',             category: 'indicators', status: 'solo',
    notes: 'Chaikin Money Flow — not in any installed competitor lib.' },
  { name: 'nvi',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Negative Volume Index. Seed = 1000. Matches tulind bit-for-bit.' },
  { name: 'pvi',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'] },
  { name: 'emv',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Ease of Movement (scale=10000). Takes [[H,L,V], …].' },
  { name: 'natr',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Normalized ATR (period=14). Composes with ta.atr.' },
  { name: 'dpo',             category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Detrended Price Oscillator (period=21). shift = floor(length/2)+1.' },
  { name: 'mass',            category: 'indicators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Mass Index (length=25, EMA period fixed at 9). Takes [[H,L], …].' },
  { name: 'ulcer',           category: 'indicators', status: 'solo',
    notes: 'Ulcer Index — not in installed competitor libs.' },
  { name: 'vortex',          category: 'indicators', status: 'solo',
    notes: 'Vortex (period=14). Returns array of [VI+, VI−] pairs.' },
  { name: 'kdj',             category: 'indicators', status: 'solo',
    notes: 'KDJ — Stochastic + J-line (3K − 2D). Returns array of [K, D, J] triples.' },

  // === oscillators ===
  { name: 'gator',       category: 'oscillators', status: 'solo' },
  { name: 'mom_osc',     category: 'oscillators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Chande CMO — tulind.cmo.' },
  { name: 'chaikin_osc', category: 'oscillators', status: 'cross-lib',
    libs: ['@debut/indicators'] },
  { name: 'ao',          category: 'oscillators', status: 'cross-lib',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'ac',          category: 'oscillators', status: 'cross-lib',
    libs: ['trading-signals'], notes: 'Williams Accelerator.' },
  { name: 'fisher',      category: 'oscillators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Tulind takes (H, L); ta.js takes (H+L)/2.' },
  { name: 'ult',         category: 'oscillators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Williams Ultimate Oscillator (default 7/14/28).' },
  { name: 'kvo',         category: 'oscillators', status: 'cross-lib',
    libs: ['tulind'], notes: 'Klinger Volume Oscillator (default 34/55). Streaming EMA seed.' },

  // === bands ===
  { name: 'bands',    category: 'bands',  status: 'cross-lib',  caseName: 'bbands',
    libs: ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'] },
  { name: 'keltner',  category: 'bands',  status: 'cross-lib',
    libs: ['technicalindicators'] },
  { name: 'don',      category: 'bands',  status: 'solo' },
  { name: 'fibbands', category: 'bands',  status: 'solo' },
  { name: 'envelope', category: 'bands',  status: 'solo' },

  // === statistics ===
  { name: 'std',         category: 'statistics', status: 'excluded',
    reason: 'scalar — companion std_series covers cross-lib rolling perf' },
  { name: 'std_series',  category: 'statistics', status: 'cross-lib', caseName: 'std',
    libs: ['technicalindicators', '@debut/indicators', 'tulind'],
    notes: 'one-pass rolling std (period=20). Cross-lib comparison runs through this case.' },
  { name: 'lr_slope',    category: 'statistics', status: 'cross-lib',
    libs: ['tulind'], notes: 'Linear regression slope (period=14). Matches tulind.linregslope.' },
  { name: 'lr_intercept', category: 'statistics', status: 'cross-lib',
    libs: ['tulind'], notes: 'Linear regression intercept (b at x=0). Matches tulind.linregintercept.' },
  { name: 'lr_angle',    category: 'statistics', status: 'solo',
    notes: 'Linear regression angle (atan(slope) in degrees). Tulind has no linregangle export.' },
  { name: 'tsf',         category: 'statistics', status: 'cross-lib',
    libs: ['tulind'], notes: 'Time Series Forecast = lsma + slope. Matches tulind.tsf.' },
  { name: 'cor',         category: 'statistics', status: 'solo',
    notes: 'Scalar — no competitor lib exposes a comparable scalar API at runtime.' },
  { name: 'recent_high', category: 'statistics', status: 'solo',
    notes: 'Returns single {index, value} pivot — semantically distinct from rolling Highest.' },
  { name: 'recent_low',  category: 'statistics', status: 'solo',
    notes: 'Returns single {index, value} pivot — semantically distinct from rolling Lowest.' },

  // Excluded — pure utilities / scalars / non-series / state-machine / async
  { name: 'sum',             category: 'statistics', status: 'excluded', reason: 'pure utility (single scalar)' },
  { name: 'variance',        category: 'statistics', status: 'excluded', reason: 'scalar (covered via std)' },
  { name: 'ncdf',            category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'normsinv',        category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'sim',             category: 'statistics', status: 'excluded', reason: 'stochastic Monte Carlo' },
  { name: 'percentile',      category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'covariance',      category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'dif',             category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'er',              category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'ar',              category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'kelly',           category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'martingale',      category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'antimartingale',  category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'permutations',    category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'expected_trails', category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'winratio',        category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'avgwin',          category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'avgloss',         category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'return_positive', category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'return_negative', category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'drawdown',        category: 'statistics', status: 'excluded', reason: 'trading scalar' },
  { name: 'median',          category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'mad',             category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'aad',             category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'se',              category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'ssd',             category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'log',             category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'exp',             category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'normalize',       category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'denormalize',     category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'normalize_pair',  category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'normalize_from',  category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'standardize',     category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'zscore',          category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'pvalue',          category: 'statistics', status: 'excluded', reason: 'pure utility' },
  { name: 'kmeans',          category: 'statistics', status: 'excluded', reason: 'iterative convergence — distinct workload' },
  { name: 'mse',             category: 'statistics', status: 'excluded', reason: 'scalar' },
  { name: 'cum',             category: 'statistics', status: 'excluded', reason: 'pure utility' },

  // === chart types ===
  { name: 'ha',  category: 'chart-types', status: 'cross-lib',
    libs: ['technicalindicators', '@debut/indicators'] },
  { name: 'ren', category: 'chart-types', status: 'cross-lib',
    libs: ['technicalindicators'] },

  // === misc ===
  { name: 'fibnumbers', category: 'misc', status: 'excluded', reason: 'data constant (Fibonacci sequence array)' },
  { name: 'times_up',   category: 'misc', status: 'excluded', reason: 'pure utility' },
  { name: 'times_down', category: 'misc', status: 'excluded', reason: 'pure utility' },

  // === experimental ===
  { name: 'support',          category: 'experimental', status: 'excluded',
    reason: 'builder API (returns object with .calculate(n))' },
  { name: 'resistance',       category: 'experimental', status: 'excluded',
    reason: 'builder API (returns object with .calculate(n))' },
  { name: 'divergence_state', category: 'experimental', status: 'excluded',
    reason: 'state machine — distinct workload' },

  // === nested groups ===
  { name: 'aroon.up',   category: 'indicators',  status: 'cross-lib', caseName: 'aroon_up',
    libs: ['tulind'] },
  { name: 'aroon.down', category: 'indicators',  status: 'cross-lib', caseName: 'aroon_down',
    libs: ['tulind'] },
  { name: 'aroon.osc',  category: 'oscillators', status: 'cross-lib', caseName: 'aroon_osc',
    libs: ['tulind'] },
  { name: 'random.prng',  category: 'random', status: 'excluded', reason: 'PRNG — not technical analysis' },
  { name: 'random.pick',  category: 'random', status: 'excluded', reason: 'PRNG — not technical analysis' },
  { name: 'random.range', category: 'random', status: 'excluded', reason: 'PRNG — not technical analysis' },
  { name: 'random.float', category: 'random', status: 'excluded', reason: 'PRNG — not technical analysis' },
  { name: 'random.order', category: 'random', status: 'excluded', reason: 'PRNG — not technical analysis' },

  // === multi (conditionally loaded — Node ≥12) ===
  { name: 'multi.sim', category: 'multi', status: 'excluded',
    reason: 'worker_threads / async — distinct methodology required' },
];
