#!/usr/bin/env node
// Coverage drift validator + COVERAGE.md renderer.
//
// Three drift checks (any failure → exit 1):
//   1. Every ta.js export has a coverage row.
//   2. Every coverage row points at an actual ta.js export.
//   3. Every cross-lib / solo coverage row has a matching cases/<category>.js
//      block whose `name` equals row.caseName ?? row.name.
//
// Pass `--md` to additionally write `bench/COVERAGE.md`.

const fs = require('node:fs');
const path = require('node:path');

const ta = require('..');
const coverage = require('./coverage.js');
const { cases } = require('./cases/index.js');

const args = process.argv.slice(2);
const WRITE_MD = args.includes('--md');

// --- Enumerate all reachable ta.js exports (top-level + one level of nesting) ---

// Nested namespaces in ta.js are these dotted exports; everything else is a
// flat top-level leaf (function or data constant).
const NESTED_NAMESPACES = new Set(['aroon', 'random', 'multi']);

function enumerateExports(reg) {
  const out = [];
  for (const k of Object.keys(reg)) {
    const v = reg[k];
    if (NESTED_NAMESPACES.has(k) && v && typeof v === 'object') {
      for (const sub of Object.keys(v)) out.push(k + '.' + sub);
    } else {
      out.push(k);
    }
  }
  return out.sort();
}

const exportNames = enumerateExports(ta);
const coverageNames = coverage.map(r => r.name);
const caseNames = new Set(cases.map(c => c.name));

// --- Drift checks ---

const errors = [];

const coverageSet = new Set(coverageNames);
for (const exp of exportNames) {
  if (!coverageSet.has(exp)) {
    errors.push(`drift: ta.js export '${exp}' has no coverage row in bench/coverage.js`);
  }
}

const exportSet = new Set(exportNames);
for (const row of coverage) {
  if (!exportSet.has(row.name)) {
    errors.push(`drift: coverage row '${row.name}' (status=${row.status}) does not match any ta.js export`);
  }
}

for (const row of coverage) {
  if (row.status !== 'cross-lib' && row.status !== 'solo') continue;
  const caseName = row.caseName ?? row.name;
  if (!caseNames.has(caseName)) {
    errors.push(`drift: coverage row '${row.name}' (status=${row.status}, caseName=${caseName}) has no matching case in bench/cases/`);
  }
}

// --- Stdout summary ---

const grouped = { 'cross-lib': [], 'solo': [], 'excluded': [] };
for (const row of coverage) (grouped[row.status] ??= []).push(row);

console.log('ta.js bench coverage');
console.log('====================');
console.log(`exports:    ${exportNames.length}`);
console.log(`coverage rows: ${coverage.length}`);
console.log(`  cross-lib: ${grouped['cross-lib'].length}`);
console.log(`  solo:      ${grouped['solo'].length}`);
console.log(`  excluded:  ${grouped['excluded'].length}`);
console.log(`cases:      ${cases.length}`);

if (errors.length) {
  console.error('\nDRIFT (' + errors.length + '):');
  for (const e of errors) console.error('  ' + e);
  process.exit(1);
}
console.log('\nno drift.');

// --- Markdown rendering ---

if (!WRITE_MD) process.exit(0);

const ALL_LIBS = ['technicalindicators', 'trading-signals', '@debut/indicators', 'tulind'];

function libVersion(name) {
  try { return require(name + '/package.json').version; } catch { return null; }
}

function libVersions() {
  return {
    'ta.js': require('../package.json').version,
    'technicalindicators': libVersion('technicalindicators'),
    'trading-signals': libVersion('trading-signals'),
    '@debut/indicators': libVersion('@debut/indicators'),
    'tulind': libVersion('tulind'),
  };
}

function escapeCell(s) {
  return String(s ?? '').replace(/\|/g, '\\|');
}

function render() {
  const lines = [];
  lines.push('# ta.js bench coverage');
  lines.push('');
  lines.push('_This file is generated by `npm run bench:coverage:write` from `bench/coverage.js`. Do not edit by hand._');
  lines.push('');
  lines.push('Total ta.js exports: **' + exportNames.length + '**.');
  lines.push('');
  lines.push('| status | count | meaning |');
  lines.push('|---|---:|---|');
  lines.push(`| cross-lib | ${grouped['cross-lib'].length} | benchmarked against ≥1 competitor library; correctness diff in BENCHMARKS.md |`);
  lines.push(`| solo      | ${grouped['solo'].length} | ta.js-only perf-regression tracking (no competitor in installed set) |`);
  lines.push(`| excluded  | ${grouped['excluded'].length} | scalar / utility / state-machine / async — not a series workload |`);
  lines.push('');

  lines.push('## Library versions');
  lines.push('| library | version |');
  lines.push('|---|---|');
  for (const [k, v] of Object.entries(libVersions())) lines.push(`| ${k} | ${v ?? '_not installed_'} |`);
  lines.push('');

  // === cross-lib matrix ===
  lines.push('## Cross-library coverage');
  lines.push('');
  lines.push('Each row is a ta.js export with comparison adapters. ✓ marks the libs whose API supports the same indicator.');
  lines.push('');
  lines.push('| function | category | ' + ALL_LIBS.map(escapeCell).join(' | ') + ' | notes |');
  lines.push('|---|---|' + ALL_LIBS.map(() => ':---:').join('|') + '|---|');
  for (const row of grouped['cross-lib']) {
    const cells = ALL_LIBS.map(l => row.libs?.includes(l) ? '✓' : '—');
    lines.push('| `' + row.name + '` | ' + row.category + ' | ' + cells.join(' | ') + ' | ' + escapeCell(row.notes ?? '') + ' |');
  }
  lines.push('');

  // === solo benches ===
  lines.push('## Solo benchmarks');
  lines.push('');
  lines.push('ta.js-unique indicators with no installed competitor. Benchmarks track ta.js perf regressions over time.');
  lines.push('');
  lines.push('| function | category | notes |');
  lines.push('|---|---|---|');
  for (const row of grouped['solo']) {
    lines.push('| `' + row.name + '` | ' + row.category + ' | ' + escapeCell(row.notes ?? '') + ' |');
  }
  lines.push('');

  // === excluded, grouped by reason ===
  lines.push('## Excluded');
  lines.push('');
  lines.push('Functions intentionally skipped — wrong workload shape for the harness, or outside the scope of comparative TA benchmarking.');
  lines.push('');
  const byReason = new Map();
  for (const row of grouped['excluded']) {
    const r = row.reason ?? 'unspecified';
    if (!byReason.has(r)) byReason.set(r, []);
    byReason.get(r).push(row.name);
  }
  for (const [reason, names] of [...byReason.entries()].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`- **${reason}** (${names.length}): ${names.map(n => '`' + n + '`').join(', ')}`);
  }
  lines.push('');

  return lines.join('\n');
}

const md = render();
fs.writeFileSync(path.join(__dirname, 'COVERAGE.md'), md);
console.log('wrote bench/COVERAGE.md');
